blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:category }

blog_posts:
    path:     /{id}
    defaults: { _controller: BlogBundle:Default:posts }

blog_search:
    path:     /search/
    defaults: { _controller: BlogBundle:Default:search }
    requirements:
        methods: POST
