BlogBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            unique: true
        image:
            type: string
            length: 255
        content:
            type: text
        createdAt:
            type: datetime
            column: created_at
    lifecycleCallbacks: {  }
