BlogBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        post_id:
            type: integer
            notnull: true
        author:
            type: string
            length: 255
        content:
            type: text
        postedAt:
            type: datetime
            column: posted_at
    lifecycleCallbacks: {  }
